services:
  provider:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        MONGO_URI: ${MONGO_URI}
        PRIVATE_KEY: ${PRIVATE_KEY}
        PUBLIC_KEY: ${PUBLIC_KEY}
        SENDER_EMAIL: ${SENDER_EMAIL}
        SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo:8.0.0-rc16
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
